import { Inter } from "next/font/google";
import "../styles/globals.scss";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#090a0c]">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>

    </html>
  );
}
