import { Inter, Manrope, Plus_Jakarta_Sans } from "next/font/google";
import "../styles/globals.scss";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({
  subsets: ['latin'],
  variable: "--font-manrope"
})
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#090a0c]">
      <body className={`${inter.className} ${manrope.variable} relative overflow-x-hidden`}>
        <Header/>
        <div>
                <img src="/assets/image/lights.svg" alt="" className="absolute top-0 left-1/2 -translate-x-1/2" />
                <img src="/assets/image/bg-shadows.svg" alt="" className="absolute top-[-500px] left-[-400px]" />
            </div>
        {children}
        <Footer />
      </body>

    </html>
  );
}
